### PR TITLE
Add display_name to package.json.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
@freaktechnik Thanks for merging so quickly! Would you mind building a new package in the near future?

**Comment by freaktechnik** [comment]
Yes, I'll submit 0.2.0 soon. If I manage to bundle it quickly tonight (approx 2 hours from now), else tomorrow.

I got the hint from your patch version change, either way ;)

**Comment by freaktechnik** [comment]
@mrstegeman I've published a 0.2.0 here as https://github.com/freaktechnik/sonos-adapter/releases/tag/v0.2.0 with the tarball, should I open a PR for it on the list repo, or can you just directly update it? (Since all my pr would do is point to the PR and bump the version number)

**Comment by mrstegeman** [comment]
Thank you! I'll go ahead and pull it in.

**Pull request merged**
